jobs:
 - name: nightly
   schedule: 0 0 * * * # This example will run every day at midnight.
   steps:
     - name: run models
       command: dbt run
     - name: test models
       command: dbt test

 - name: every_15_mins
   schedule: 0 0/15 * * * # This example will run every 15mins
   steps:
     - name: run models
       command: dbt run
