-- Create object access role for account usage read
USE ROLE SECURITYADMIN;
CREATE ROLE SNOWFLAKE_ACCOUNT_USAGE_IMPORTED_PRIVILEGES;
GRANT ROLE SNOWFLAKE_ACCOUNT_USAGE_IMPORTED_PRIVILEGES TO ROLE SYSADMIN; // always do this

-- Grant permissions to new OA role
USE ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOWFLAKE_ACCOUNT_USAGE_IMPORTED_PRIVILEGES;

-- Grant access to the OA to appropriate BF roles
USE ROLE SECURITYADMIN;
GRANT ROLE SNOWFLAKE_ACCOUNT_USAGE_IMPORTED_PRIVILEGES TO ROLE RTE;
GRANT ROLE SNOWFLAKE_ACCOUNT_USAGE_IMPORTED_PRIVILEGES TO ROLE FIVETRAN_SERVICE_ACCOUNT_ROLE;
