SELECT
  CONVERT_TIMEZONE('America/Chicago', START_TIME)::TIMESTAMP_NTZ AS START_TIME_CT,
  CONVERT_TIMEZONE('America/Chicago', END_TIME)::TIMESTAMP_NTZ AS END_TIME_CT,
  WAREHOUSE_ID,
  WAREHOUSE_NAME,
  CREDITS_USED,
  CREDITS_USED_COMPUTE,
  CREDITS_USED_CLOUD_SERVICES

FROM
  {{ref('stg_warehouse_metering_history')}}